## Compose specification version is omitted to use the latest syntax.

services:
  finetune:
    build:
      context: .
    volumes:
      - ./data:/app/data
      - /mnt/sdb/data/ai/models/model_output:/app/model_output
      - ~/.cache/huggingface:/root/.cache/huggingface  # Cache HF models
    environment:
      - PYTHONUNBUFFERED=1
      - HF_HUB_CACHE=/root/.cache/huggingface
      - TRANSFORMERS_CACHE=/root/.cache/huggingface
    networks:
      - ai_network
    # This is a one-time training job, not a service
    # Remove healthcheck and use restart policy
    command:
      - python
      - train.py
      - --base_model_name
      - Qwen/Qwen2.5-VL-7B-Instruct
      - --train_file
      - data/train.jsonl
      - --eval_file
      - data/eval.jsonl
      - --output_dir
      - /app/model_output
      - --num_epochs
      - "3"  # Increased for better training
      - --per_device_batch_size
      - "1"
      - --learning_rate
      - "5e-5"
      - --use_lora  
    # Don't restart automatically - it's a one-time job
    restart: "no"

  api:
    build:
      context: ./server
    volumes:
      - /mnt/sdb/data/ai/models/model_output:/app/model_output:ro
      - ~/.cache/huggingface:/root/.cache/huggingface:ro
    environment:
      - MODEL_PATH=/app/model_output
      - BASE_MODEL_NAME=Qwen/Qwen2.5-VL-7B-Instruct
      - HF_HUB_CACHE=/root/.cache/huggingface
    ports:
      - "8000:8000"
    networks:
      - ai_network
    # Wait for training to complete before starting API
    depends_on:
      - finetune
    restart: unless-stopped
    # Add healthcheck for API
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health', timeout=5).raise_for_status()"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - "8080:8080"
    environment:
      # Disable authentication for ease of use in local setups
      - WEBUI_AUTH=false
      
      # Disable features that require internet
      - ENABLE_RAG_WEB_SEARCH=false
      - ENABLE_RAG_WEB_LOADER=false
      - ENABLE_MODEL_FILTER=false
      - OPENAI_API_BASE_URL=http://api:8000/v1
      - OPENAI_API_KEY=dummy
      - DEFAULT_MODELS=qwen-finetuned
      - MODEL_ID=Qwen/Qwen2.5-VL-7B-Instruct
      - LLM_ADAPTER=/app/model_output
    volumes:
      - openwebui_data:/data
      - /mnt/sdb/data/ai/models/model_output:/app/model_output:ro
      - ~/.cache/huggingface:/root/.cache/huggingface:ro
    networks:
      - ai_network
    depends_on:
      - api
    restart: unless-stopped

networks:
  ai_network:
    driver: bridge

volumes:
  openwebui_data:
